<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTfm)-windows</TargetFramework>
    <AssemblyTitle>S#.DesktopDriver.Wpf</AssemblyTitle>
    <Description>Reads, drives and pictures WPF controls for StockSharp DesktopDriver.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopDriver.Runtime\DesktopDriver.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="StockSharp.DesktopDriver.Wpf.Tests" />
  </ItemGroup>

</Project>
